name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . pytest

      - name: Run pytest
        run: pytest

  unsigned-routes:
    name: Post unsigned route checks
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python-gswap-sdk
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Run unsigned route checks
        id: unsigned
        env:
          INPUT_TOKEN: "GALA|Unit|none|none"
          OUTPUT_TOKEN: "GUSDC|Unit|none|none"
          INPUT_AMOUNT: "1"
          OUTPUT_AMOUNT: "1"
          POOL_FEE: "500"
          WALLET_ADDRESS: "eth|742d35Cc6634C0532925a3b844Bc454e4438f44e"
          ASSETS_PAGE: "1"
          ASSETS_LIMIT: "5"
        run: |
          python scripts/run_unsigned_route_checks.py \
            --json-output unsigned_routes.json \
            --markdown-output unsigned_routes.md
          {
            echo 'markdown<<EOF'
            cat unsigned_routes.md
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          {
            echo 'json<<EOF'
            cat unsigned_routes.json
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Comment unsigned route results on PR
        uses: actions/github-script@v7
        env:
          MARKDOWN: ${{ steps.unsigned.outputs.markdown }}
        with:
          script: |
            const marker = '<!-- gswap-unsigned-routes -->';
            const body = process.env.MARKDOWN;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existing = comments.find(comment => comment.body.includes(marker));

            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }
          
